# Here we are writing comose file to automate docker steps like image run, port mapping, volume creation

services:                       # default synstax
  frontendnginxfirst:           # naming convention for container
    build: /root/Docker_labs/Nginx_dockerfile  # location of dockerfile which we have to run
    ports:
      - '80:80'              # exposing port
    container_name: nginxfrontendcontainer # providing name to container 
    volumes:
      - myvol: /usr/share/nginx/html  # adding volume  
    network_mode: 
      bridge

